// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAR2FWgnjodoAFGIQEq0QXbuMJPDr5uqVI',
    appId: '1:158727119498:web:8c3a09df0cd22add598373',
    messagingSenderId: '158727119498',
    projectId: 'flutterfirechat1',
    authDomain: 'flutterfirechat1.firebaseapp.com',
    storageBucket: 'flutterfirechat1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHfQW-Wnv0SmR-Ko9psTSj_PorbHL8H80',
    appId: '1:158727119498:android:bdd1947ae052bc75598373',
    messagingSenderId: '158727119498',
    projectId: 'flutterfirechat1',
    storageBucket: 'flutterfirechat1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-gjY6lZn9xS-JBYYqIqAe4R0DsgRpTi0',
    appId: '1:158727119498:ios:c9658f04548c14df598373',
    messagingSenderId: '158727119498',
    projectId: 'flutterfirechat1',
    storageBucket: 'flutterfirechat1.appspot.com',
    iosClientId: '158727119498-i56otm3urc78r7g8pb581usev40cs1i9.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterfirechat1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-gjY6lZn9xS-JBYYqIqAe4R0DsgRpTi0',
    appId: '1:158727119498:ios:a84f3c4cff72a2b7598373',
    messagingSenderId: '158727119498',
    projectId: 'flutterfirechat1',
    storageBucket: 'flutterfirechat1.appspot.com',
    iosClientId: '158727119498-1cqqtme00rigjlj0hkf956sigci8ctqf.apps.googleusercontent.com',
    iosBundleId: 'com.macflutterfirechat.app',
  );
}
